spring:
  application:
    name: server
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  server:
    url: ${AI_SERVER:http://localhost:8000}

upload:
  temp-dir: uploads/temp
  flowers-dir: uploads/flowers
  expiry-hours: 1
